//go:build !ignore_autogenerated

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is a deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AIInsight) DeepCopyInto(out *AIInsight) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is a deepcopy function, copying the receiver, creating a new AIInsight.
func (in *AIInsight) DeepCopy() *AIInsight {
	if in == nil {
		return nil
	}
	out := new(AIInsight)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is a deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AIInsight) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is a deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AIInsightList) DeepCopyInto(out *AIInsightList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]AIInsight, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is a deepcopy function, copying the receiver, creating a new AIInsightList.
func (in *AIInsightList) DeepCopy() *AIInsightList {
	if in == nil {
		return nil
	}
	out := new(AIInsightList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is a deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AIInsightList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is a deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AIInsightSpec) DeepCopyInto(out *AIInsightSpec) {
	*out = *in
	out.Target = in.Target
	if in.ContextHints != nil {
		in, out := &in.ContextHints, &out.ContextHints
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is a deepcopy function, copying the receiver, creating a new AIInsightSpec.
func (in *AIInsightSpec) DeepCopy() *AIInsightSpec {
	if in == nil {
		return nil
	}
	out := new(AIInsightSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is a deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AIInsightStatus) DeepCopyInto(out *AIInsightStatus) {
	*out = *in
	if in.CompletedAt != nil {
		in, out := &in.CompletedAt, &out.CompletedAt
		*out = (*in).DeepCopy()
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is a deepcopy function, copying the receiver, creating a new AIInsightStatus.
func (in *AIInsightStatus) DeepCopy() *AIInsightStatus {
	if in == nil {
		return nil
	}
	out := new(AIInsightStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is a deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AIInsightTarget) DeepCopyInto(out *AIInsightTarget) {
	*out = *in
}

// DeepCopy is a deepcopy function, copying the receiver, creating a new AIInsightTarget.
func (in *AIInsightTarget) DeepCopy() *AIInsightTarget {
	if in == nil {
		return nil
	}
	out := new(AIInsightTarget)
	in.DeepCopyInto(out)
	return out
}
